const events = [
    {
      "title": "Speed Dating",
      "day of week": "Friday",
      "date": "2024-01-19",
      "time": "8-9:30PM",
      "location": "Lot 22/ Phelps 1160",
      "customTime": "",
      "ready": "Yes"
    },
    {
      "title": "GM #1",
      "day of week": "Monday",
      "date": "2024-01-22",
      "time": "8-10PM",
      "location": "TD-W 1701",
      "customTime": "",
      "ready": "Yes"
    },
    {
      "title": "Field Day",
      "day of week": "Friday",
      "date": "2024-01-26",
      "time": "3-5PM",
      "location": "Student Health Lawn",
      "customTime": "",
      "ready": "Yes"
    },
    {
      "title": "TFTI",
      "day of week": "Saturday",
      "date": "2024-01-27",
      "time": "Overnight",
      "location": "UCLA (Mesa Lawn)",
      "customTime": "Overnight",
      "ready": "Yes"
    },
    {
      "title": "Winter Big/Little Reveal",
      "day of week": "Sunday",
      "date": "2024-02-04",
      "time": "2-4PM",
      "location": "Top of Lot 22",
      "customTime": "",
      "ready": "Yes"
    },
    {
      "title": "GM #2",
      "day of week": "Monday",
      "date": "2024-02-05",
      "time": "8-10PM",
      "location": "TD-W 1701",
      "customTime": "",
      "ready": "Yes"
    },
    {
      "title": "TASA Online Game Night\n",
      "day of week": "Wednesday",
      "date": "2024-02-07",
      "time": "8:00 PM",
      "location": "Online (Discord)",
      "customTime": "",
      "ready": "Yes"
    },
    {
      "title": "Mahjong Mocktails",
      "day of week": "Thursday",
      "date": "2024-02-08",
      "time": "8-10PM ",
      "location": "Girvetz 1115",
      "customTime": "",
      "ready": "Yes"
    },
    {
      "title": "NSU x TASA",
      "day of week": "Friday",
      "date": "2024-02-09",
      "time": "5-7; 9-12AM",
      "location": "Girvetz 1004",
      "customTime": "",
      "ready": "Yes"
    },
    {
      "title": "Lunar New Year Hotpot Night!",
      "day of week": "Saturday",
      "date": "2024-02-10",
      "time": "6-9PM",
      "location": "Multi Cultural Center",
      "customTime": "",
      "ready": "Yes"
    },
    {
      "title": "TASA Talks",
      "day of week": "Thursday",
      "date": "2024-02-15",
      "time": "8-10PM",
      "location": "Girvetz 1116",
      "customTime": "",
      "ready": "Yes"
    },
    {
      "title": "winbert",
      "day of week": "sunday",
      "date": "2024-03-09",
      "time": "1-5 AM ",
      "location": "Online",
      "customTime": "",
      "ready": "Yes"
    },
    {
      title: "TASA Winter Retreat",
      date: "2024-1-13",
      startTime: "Overnight",
      endTime: "",
      location: "Frazier Park",
      customTime: "Overnight",
    },
    {
      title: "Winter GM 1 W/ Hochaya",
      date: "2024-1-22",
      startTime: "20:00",
      endTime: "22:00",
      location: "TD-W 1701",
      customTime: "",
    },
    {
      title: "Pickup Coloring Night!",
      date: "2024-1-24",
      startTime: "20:00",
      endTime: "22:00",
      location: "Arts 1353, 1356, 1349",
      customTime: "",
    },
    {
      title: "Field Day!",
      date: "2024-1-26",
      startTime: "15:00",
      endTime: "17:00",
      location: "Student Health Lawn",
      customTime: "",
    },
    {
      title: "TASA x UCLA TFTI",
      date: "2024-1-27",
      startTime: "Overnight",
      endTime: "",
      location: "UCLA",
      customTime: "Overnight",
    },
    {
      title: "Winter Big Little Reveal",
      date: "2024-2-4",
      startTime: "14:00",
      endTime: "16:00",
      location: "Top of Lot 22",
      customTime: "",
    },
    {
      title: "Winter GM #2",
      date: "2024-2-5",
      startTime: "20:00",
      endTime: "22:00",
      location: "TD-W 1701",
      customTime: "",
    },
    {
      title: "TASA Online Game Night",
      date: "2024-2-7",
      startTime: "20:00",
      endTime: "22:00",
      location: "Discord",
      customTime: "",
    },
    {
      title: "Mahjong and Mocktails",
      date: "2024-2-8",
      startTime: "20:00",
      endTime: "22:00",
      location: "Girvetz 1115",
      customTime: "",
    },
    {
      title: "NSU x TASA",
      date: "2024-2-9",
      startTime: "17:00",
      endTime: "19:00",
      location: "Girvetz 1004",
      customTime: "",
    },
    {
      title: "LNY Hotpot Night!",
      date: "2024-2-10",
      startTime: "18:30",
      endTime: "21:00",
      location: "Multi Cultural Center",
      customTime: "",
    },
    {
      title: "TASA Talks",
      date: "2024-2-15",
      startTime: "20:00",
      endTime: "22:00",
      location: "Girvetz 1116",
      customTime: "",
    },
    {
      title: "Capture the Moment Intern Event",
      date: "2024-3-3",
      startTime: "14:00",
      endTime: "17:00",
      location: "Chem Lawn",
      customTime: "",
    },
    {
      title: "TASA Talks",
      date: "2024-3-7",
      startTime: "18:00",
      endTime: "19:00",
      location: "HSSB 1174",
      customTime: "",
    },
  ];
  
  export default events;
  